apiVersion: v1
kind: Service
metadata:
  name: {{ include "couponservicechart.fullname" . }}
  labels:
    {{- include "couponservicechart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: tomcat
  selector:
    {{- include "couponservicechart.selectorLabels" . | nindent 4 }}
